### ISSUE TITLE
Polymorphism in Attributes for AUXIP

### ISSUE THREAD

**Issue by BenEsquis** [reprocessing-reference/preparation#33]
Dear, 

We currently have an issue on the polymorphism on attributes in the AUXIP interface. 
At this time we can't have:

"Attributes": [
                {
                    "@odata.type": "#OData.CSC.StringAttribute",
                    "Name": "datastripId",
                    "ValueType": "String",
                    "Value": "S2B_OPER_MSI_L0__DS_EPAE_20201007T110039_S20201007T083226_N02.09"
                },              
                {
                    "@odata.type": "#OData.CSC.DateTimeOffsetAttribute",
                    "Name": "processingDate",
                    "ValueType": "DateTimeOffset",
                    "Value": "2020-10-07T11:00:39.000Z"
                }
]

Modifying the code could be rather complex so we wonder it is possible to map all the type to StringAttributes ? as any SubType (Integer/Double...) can be mapped to a StringAttribute. For example:

"Attributes": [
                {
                    "@odata.type": "#OData.CSC.StringAttribute",
                    "Name": "datastripId",
                    "ValueType": "String",
                    "Value": "S2B_OPER_MSI_L0__DS_EPAE_20201007T110039_S20201007T083226_N02.09"
                },              
                {
                    "@odata.type": "#OData.CSC.StringAttribute",
                    "Name": "processingDate",
                    "ValueType": "DateTimeOffset",
                    "Value": "2020-10-07T11:00:39.000Z"
                },              
                {
                    "@odata.type": "#OData.CSC.StringAttribute",
                    "Name": "Orbit",
                    "ValueType": "Int64",
                    "Value": "100"
                }
]

The only differences would be the quotes "" on the Value and the fact that the comparison in the odata queries will be string litteral comparison instead of the initial type comparison.

So do you think we can do this ? Or do we modify our code to support the current ICD definition ?

Regards.

**Comment by BogdanaTsonevska** [comment]
email sent to the AUXIP ICD Technical Authority for approval

**Comment by BogdanaTsonevska** [comment]
Dear all, 

I need to ask you to be compliant with the ICD. Not obligatory for the delivery of V0.1 foreseen on 15/01. We should see what this changes apply in terms of schedule and if it is OK for the delivery of V1.
Regards,
Bogdana 

----- Forwarded by Bogdana Tsonevska/esrin/ESA on 11/01/2021 10:39 -----

From:	Razvan Cosac/esrin/ESA
To:	Bogdana Tsonevska/esrin/ESA@ESA
Date:	11/01/2021 09:49
Subject:	Re: AUXIP issue :polymorphism on attributes


Hi Bogdana,

This is related to the Auxiliary Data Gathering, correct? Normally they should follow the ICD, so they should align this to the ICD - otherwise they are not compliant. Now, I'm not sure about how much this change would take in terms of time and resources.

Attributes are not that important, at least not initially, but when supported they have to follow the ICD, otherwise we will end up with different implementations from everyone.


Regards,
Razvan
