### ISSUE TITLE
AUXIP Catalog export access

### ISSUE THREAD

**Issue by BenEsquis** [reprocessing-reference/preparation#44]
Dear,

About the Catalog snapshots described in the AUXIP ICD 3.3.3,

There is no specification on how these archives are accessed, is this an FTP ? on the S3 ?

Also when the file has not changed, we suggest not to redo it but to give the link to the lastUpdated json.

Regards

**Comment by BogdanaTsonevska** [comment]
emil sent to AUXIP ICD creator.

**Comment by BogdanaTsonevska** [comment]
Dear Bogdana,

I may be missing some context, but I will try to answer.

Regarding how these are accessed, it is true that it is not specified, and we will provide this clarification in the next update. It should be through a simple HTTP file interface with the same authentication as the AUXIP.

I think the last updated JSON is fine when the file has not changed, rather than recreating the file.

Regards,
Razvan

**Comment by BenEsquis** [comment]
Dear,

Do we need to keep all the snapshot of each days or do we only keep the last one generated ?

Also if we keep all the snapshots we will need to put a maximum number of snapshots in order not to overflow the storage.

Regards

**Comment by BogdanaTsonevska** [comment]
Dear,
Could we keep 1 month of snapshots? All the snapshots should be stored on the cloud once evited. 
Regards,
Bogdana
