### ISSUE TITLE
Catalogue Export Naming Attributes issue

### ISSUE THREAD

**Issue by BenEsquis** [reprocessing-reference/preparation#45]
Dear,

In 3.3.3 Catalogue export of the AUXIP ICD it is written

> - AUX_XYZ7characters corresponding to the Auxiliarysystem, where XYZ represents the AUX provider:o
> ADG = Aux Data Gatheringo
> POD = Precise Orbit Determinationo
> C-V = Cal/Val3

Were do we find these informations from an AUXIP Product, knowing that the AUXIP elements are all generics with only few attributes to describe them.

Regards.

**Comment by BogdanaTsonevska** [comment]
Dear all, 
The only way to deal with this issue is to assign the providers manually (I imagine that it is easier) to the All_Aux table. 
This information is available in Sentinel-1,2,3 Product Unit Definition and Metadata ICD. 
ADG is ECMWF, etc (everything except POD and CAL&Val (MPC)). 
Sentinel-2 Product Unit Definition and Metadata ICD: has a typo the  AUX_PREORB and AUX_RESORB are POD and not CAL&VAL MPC, but this doesn't really impact us. 
Regards,
Bogdana

**Comment by BenEsquis** [comment]
Dear,

For S2 the table in the ICD seems ok.
However there is no "DataProvider" in the S1 ICD pdf document and in S3 there are various provider that doesn't seems to correspond to the one needed.

![image.png](https://images.zenhubusercontent.com/5f8021dc20042c34dcd49bca/b8f2091e-92f2-46e7-b87b-7a8705edc210)

Regards

**Comment by BogdanaTsonevska** [comment]
Hi, 
All the auxiliary that are not Cal (MPC) or POD should be tagged ADG. 
Regards,
Bogdana

**Comment by BenEsquis** [comment]
Dear Bogdana,

Did you find the meaning of MPMF in the S3 ICD file ?

Is it MPC ?

Regards

**Comment by cbouzina** [comment]
MPMF = Mission Performance Monitoring Facility (it generates several reports and plots for QC)

**Comment by BogdanaTsonevska** [comment]
It is confirmed the MPMF is MPC.
