### ISSUE TITLE
Download Quotas : TotalDownloadsQuota & ParallelDownloadsQuota

### ISSUE THREAD

**Issue by nmeskini** [reprocessing-reference/preparation#51]
Hi Bogdana,

We need clarification about “Download Quotas” 
- TotalDownloadsQuota: ( Maximum volume (GB) transfer within a defined period ) 
•	Is this threshold (quota) client dependent or it is applicable to all clients? 
•	What is the value of this quota? 
•	What is the time duration (period) to be considered?
- ParallelDownloadsQuota: (Maximum number of separate downloads which can be performed in
Parallel) 
•	What is the value of this threshold?

Best Regards,

Naceur MESKINI.

**Comment by BogdanaTsonevska** [comment]
Dear Naceur,
I would need your assessment for these questions. My needs are two :
1/what satisfies the auxiliary for processing: 
-the download capacity 5Gbps, each auxiliary data items may be downloaded up to 10times. (ParallelDownloadsQuota). In total, we have around 7TB traffic per year.

2/ what satisfies the reprocessing : 
-There is not parallel downloads for the same data. There are minimum 5 downloads in parallel for different aux data.  Nevertheless, the volumes are higher, so maybe is clever that a user can simultaneously download different auxiliary data files in parallel in order to download the total volume quickly. We should size for the worst case (biggest data volume), for example,, all aux data for  S3 for one instrument (the one with higher volume, may be it is SRAL or OLCI) (could you check if we are speaking of around 8TB). For a period 3 day to download all is a good target.  

 The data volume is always increasing with a known factor (7TB per year for all Sentinels ) but we should size for that as well. 
Regards,
Bogdana

**Comment by cbouzina** [comment]
This is OK and agreed.
